"""
Django settings for smart_presence project.

Generated by Antigravity AI Assistant.
Gaya koding di bawah ini dibuat dengan dokumentasi bahasa Indonesia
agar sangat mudah dipahami oleh pemula.
"""

from pathlib import Path

# BASE_DIR menunjuk ke folder root proyek (smart-presence/)
BASE_DIR = Path(__file__).resolve().parent.parent

# Kunci rahasia untuk keamanan (Harap ganti di lingkungan produksi!)
SECRET_KEY = 'django-insecure-smart-presence-super-secret-key-12345'

# Aktifkan mode DEBUG untuk pengembangan lokal
DEBUG = True

# Izinkan semua host mengakses server dalam mode pengembangan
ALLOWED_HOSTS = ['*']


# Aplikasi yang terpasang di proyek Django Anda
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'karyawan',
    'presensi',
]

# Middleware untuk memproses request dan response
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Menunjuk ke berkas routing URL utama
ROOT_URLCONF = 'smart_presence.urls'

# Konfigurasi folder Templates HTML global
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Menambahkan folder 'templates' di root agar bisa diakses secara global
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'karyawan.context_processors.role_context',
            ],
        },
    },
]

# Konfigurasi aplikasi server WSGI & ASGI
WSGI_APPLICATION = 'smart_presence.wsgi.application'
ASGI_APPLICATION = 'smart_presence.asgi.application'


# Konfigurasi Koneksi Database MySQL
# CATATAN: Pastikan MySQL Server Anda aktif dan database 'smart_presence' sudah dibuat
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'smart_presence',      # Nama database Anda
        'USER': 'root',                # Username default MySQL (XAMPP/Laragon biasanya 'root')
        'PASSWORD': '',                # Password default MySQL (kosong untuk lokal)
        'HOST': '127.0.0.1',           # Alamat server lokal
        'PORT': '3306',                # Port default MySQL
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Validasi keamanan password pengguna Django
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Konfigurasi Bahasa dan Zona Waktu Indonesia
LANGUAGE_CODE = 'id'                # Antarmuka admin menggunakan bahasa Indonesia
TIME_ZONE = 'Asia/Jakarta'          # Zona waktu WIB (Waktu Indonesia Barat)
USE_I18N = True
USE_TZ = True


# Konfigurasi Aset Statis (CSS, JavaScript, Gambar)
# URL akses untuk file statis di browser
STATIC_URL = 'static/'

# Folder statis global tempat Anda meletakkan CSS, JS, dan Gambar kustom
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Folder tempat mengumpulkan file statis saat deploy produksi (via collectstatic)
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Konfigurasi File Media (Untuk file/gambar yang diunggah pengguna)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Tipe primary key bawaan untuk model Django
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Konfigurasi Redirect URL Autentikasi
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

