# Generated by Django 4.2 on 2026-05-20 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('jabatan', models.CharField(max_length=100, verbose_name='Jabatan')),
                ('divisi', models.CharField(max_length=100, verbose_name='Divisi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pegawai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pegawai',
                'verbose_name_plural': 'Pegawai',
            },
        ),
    ]
