# Generated by Django 5.0.14 on 2026-06-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('pegawai', 'Pegawai')], default='pegawai', max_length=20, verbose_name='Role'),
        ),
    ]
