# Generated by Django 4.2 on 2026-05-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('jam_masuk', models.TimeField(blank=True, null=True, verbose_name='Jam Masuk')),
                ('jam_pulang', models.TimeField(blank=True, null=True, verbose_name='Jam Pulang')),
                ('status_kehadiran', models.CharField(choices=[('Hadir', 'Hadir'), ('Terlambat', 'Terlambat'), ('Izin', 'Izin'), ('Alpa', 'Alpa')], default='Hadir', max_length=15, verbose_name='Status Kehadiran')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='karyawan.pegawai', verbose_name='Pegawai')),
            ],
            options={
                'verbose_name': 'Presensi',
                'verbose_name_plural': 'Daftar Presensi',
                'unique_together': {('pegawai', 'tanggal')},
            },
        ),
    ]
