# Generated by Django 4.2 on 2026-05-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
        ('presensi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanIzin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_izin', models.CharField(choices=[('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Cuti', 'Cuti')], max_length=10, verbose_name='Jenis Izin')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai')),
                ('alasan', models.TextField(verbose_name='Alasan')),
                ('bukti_file', models.FileField(blank=True, null=True, upload_to='bukti_izin/', verbose_name='Bukti File')),
                ('status_persetujuan', models.CharField(choices=[('Pending', 'Pending'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Pending', max_length=15, verbose_name='Status Persetujuan')),
                ('catatan_admin', models.TextField(blank=True, null=True, verbose_name='Catatan Admin')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_izin', to='karyawan.pegawai', verbose_name='Pegawai')),
            ],
            options={
                'verbose_name': 'Pengajuan Izin',
                'verbose_name_plural': 'Daftar Pengajuan Izin',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
