# Generated by Django 5.0.14 on 2026-06-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0002_pengajuanizin'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presensi',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
