# Generated by Django 5.0.14 on 2026-06-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0003_presensi_latitude_presensi_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presensi',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='presensi',
            name='longitude',
        ),
    ]
